name: CI

on:
  push: { branches: [main] }
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pipx install uv

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Install project (dev)
        run: uv pip install --system -e .[dev]

      - name: Ruff lint
        run: ruff check .
        continue-on-error: true

      - name: Ruff format check
        run: ruff format --check .
        continue-on-error: true

      - name: Mypy
        run: mypy src
        continue-on-error: true

      - name: Tests
        run: pytest -q
        continue-on-error: true

  build:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pipx install build
      - run: python -m build
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pipx install uv
      - run: uvx --from mkdocs mkdocs --version
      - name: Build docs
        run: uvx --with mkdocs-material mkdocs build --strict
      - name: Deploy to GitHub Pages
        run: uvx --with mkdocs-material mkdocs gh-deploy --force
