name: Docs
on:
  push: { branches: [main] }
  workflow_dispatch:
permissions:
  contents: write   # нужно для gh-deploy (push в gh-pages)

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pipx install uv
      - run: uv pip install mkdocs mkdocs-material
      - run: uv run mkdocs --version
      - run: uv run mkdocs build --strict
      - run: uv run mkdocs gh-deploy --force