name: Docs
on:
  push: { branches: [main] }
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pipx install mkdocs-material
      - run: mkdocs build --strict
      - run: mkdocs gh-deploy --force
