name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
      - "*.*.*" 

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pipx install uv

      - name: Show versions
        run: |
          python -V
          uvx --version || true

      - name: Build sdist and wheel
        run: uvx build

      - name: Verify version matches tag if tag present
        shell: bash
        run: |
          PKG_VER=$(python - <<'PY'
from pathlib import Path
import tomllib
d=tomllib.loads(Path("pyproject.toml").read_text())
print(d["project"]["version"])
PY
)
          echo "pyproject version: ${PKG_VER}"

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            RAW_TAG="${GITHUB_REF_NAME}"
            TAG_VER="${RAW_TAG#v}"
            echo "tag version: ${TAG_VER}"
            test "${PKG_VER}" = "${TAG_VER}" || { echo "Version mismatch"; exit 1; }
          fi

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # skip-existing: true
          verbose: true
