name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pipx install uv
      - run: uvx build
      - uses: pypa/gh-action-pypi-publish@release/v1
